#ifndef HYPEROS_KERNEL_UTILITIES_LOGGER_H_
#define HYPEROS_KERNEL_UTILITIES_LOGGER_H_

#define COLOR_FOREGROUND_BLACK "\033[30m"
#define COLOR_FOREGROUND_RED "\033[31m"
#define COLOR_FOREGROUND_GREEN "\033[32m"
#define COLOR_FOREGROUND_ORANGE "\033[33m"
#define COLOR_FOREGROUND_BLUE "\033[34m"
#define COLOR_FOREGROUND_MAGENTA "\033[35m"
#define COLOR_FOREGROUND_CYAN "\033[36m"
#define COLOR_FOREGROUND_LIGHT_GRAY "\033[37m"
#define COLOR_FOREGROUND_RESET "\033[39m"

#define COLOR_BACKGROUND_BLACK "\033[40m"
#define COLOR_BACKGROUND_RED "\033[41m"
#define COLOR_BACKGROUND_GREEN "\033[42m"
#define COLOR_BACKGROUND_ORANGE "\033[43m"
#define COLOR_BACKGROUND_BLUE "\033[44m"
#define COLOR_BACKGROUND_MAGENTA "\033[45m"
#define COLOR_BACKGROUND_CYAN "\033[46m"
#define COLOR_BACKGROUND_LIGHT_GRAY "\033[47m"
#define COLOR_BACKGROUND_RESET "\033[49m"

void info(const char* format, ...);
void warning(const char* format, ...);
void error(const char* format, ...);
void debug(const char* format, ...);

#endif // HYPEROS_KERNEL_UTILITIES_LOGGER_H_
