#ifndef HYPEROS_USERLAND_LIBRARIES_LIBC_LIMITS_H_
#define HYPEROS_USERLAND_LIBRARIES_LIBC_LIMITS_H_

#include <stdint.h>

#define PATH_MAX 4096

#define INT_MAX INT32_MAX
#define INT_MIN INT32_MIN

#endif