#ifndef HYPEROS_KERNEL_MEMORY_UTILITIES_H_
#define HYPEROS_KERNEL_MEMORY_UTILITIES_H_

#define BYTE_SIZE 8
#define PAGE_SIZE 4096
#define PHYSICAL_MEMORY_OFFSET 0xFFFF800000000000
#define KERNEL_BASE_ADDRESS 0xFFFFFFFF80000000

#endif // HYPEROS_KERNEL_MEMORY_UTILITIES_H_
