#ifndef HYPEROS_KERNEL_DRIVERS_QWERTZ_H_
#define HYPEROS_KERNEL_DRIVERS_QWERTZ_H_

#include "virtual_key.h"

#include <stdint.h>

uint16_t qwertz_keyboard_map[128] =
{
	VIRTUAL_KEY_UNKNOWN, VIRTUAL_KEY_UNKNOWN,
	VIRTUAL_KEY_1, VIRTUAL_KEY_2, VIRTUAL_KEY_3, VIRTUAL_KEY_4, VIRTUAL_KEY_5,
	VIRTUAL_KEY_6, VIRTUAL_KEY_7, VIRTUAL_KEY_8, VIRTUAL_KEY_9, VIRTUAL_KEY_0,
	VIRTUAL_KEY_UNKNOWN, VIRTUAL_KEY_UNKNOWN, VIRTUAL_KEY_UNKNOWN, VIRTUAL_KEY_UNKNOWN,
	// 16
	VIRTUAL_KEY_Q, VIRTUAL_KEY_W, VIRTUAL_KEY_E, VIRTUAL_KEY_R,
	VIRTUAL_KEY_T, VIRTUAL_KEY_Z, VIRTUAL_KEY_U, VIRTUAL_KEY_I,
	VIRTUAL_KEY_O, VIRTUAL_KEY_P,
	VIRTUAL_KEY_UNKNOWN, VIRTUAL_KEY_UNKNOWN, VIRTUAL_KEY_UNKNOWN, VIRTUAL_KEY_UNKNOWN,
	// 30
	VIRTUAL_KEY_A, VIRTUAL_KEY_S, VIRTUAL_KEY_D, VIRTUAL_KEY_E,
	VIRTUAL_KEY_F, VIRTUAL_KEY_G, VIRTUAL_KEY_H, VIRTUAL_KEY_J,
	VIRTUAL_KEY_K, VIRTUAL_KEY_L,
	VIRTUAL_KEY_UNKNOWN, VIRTUAL_KEY_UNKNOWN, VIRTUAL_KEY_UNKNOWN, VIRTUAL_KEY_UNKNOWN,
	// 44
	VIRTUAL_KEY_Y, VIRTUAL_KEY_X, VIRTUAL_KEY_C, VIRTUAL_KEY_V,
	VIRTUAL_KEY_B, VIRTUAL_KEY_N, VIRTUAL_KEY_M
};

#endif // HYPEROS_KERNEL_DRIVERS_QWERTZ_H_