#ifndef HYPEROS_VIRTUAL_KEY_H_
#define HYPEROS_VIRTUAL_KEY_H_

enum
{
	VIRTUAL_KEY_UNKNOWN,

	/* Printable keys */
	VIRTUAL_KEY_SPACE,
	VIRTUAL_KEY_APOSTROPHE, /* ' */
	VIRTUAL_KEY_COMMA, /* , */
	VIRTUAL_KEY_MINUS, /* - */
	VIRTUAL_KEY_PERIOD, /* . */
	VIRTUAL_KEY_SLASH, /* / */
	VIRTUAL_KEY_0,
	VIRTUAL_KEY_1,
	VIRTUAL_KEY_2,
	VIRTUAL_KEY_3,
	VIRTUAL_KEY_4,
	VIRTUAL_KEY_5,
	VIRTUAL_KEY_6,
	VIRTUAL_KEY_7,
	VIRTUAL_KEY_8,
	VIRTUAL_KEY_9,
	VIRTUAL_KEY_SEMICOLON, /* ; */
	VIRTUAL_KEY_EQUAL, /* = */
	VIRTUAL_KEY_A,
	VIRTUAL_KEY_B,
	VIRTUAL_KEY_C,
	VIRTUAL_KEY_D,
	VIRTUAL_KEY_E,
	VIRTUAL_KEY_F,
	VIRTUAL_KEY_G,
	VIRTUAL_KEY_H,
	VIRTUAL_KEY_I,
	VIRTUAL_KEY_J,
	VIRTUAL_KEY_K,
	VIRTUAL_KEY_L,
	VIRTUAL_KEY_M,
	VIRTUAL_KEY_N,
	VIRTUAL_KEY_O,
	VIRTUAL_KEY_P,
	VIRTUAL_KEY_Q,
	VIRTUAL_KEY_R,
	VIRTUAL_KEY_S,
	VIRTUAL_KEY_T,
	VIRTUAL_KEY_U,
	VIRTUAL_KEY_V,
	VIRTUAL_KEY_W,
	VIRTUAL_KEY_X,
	VIRTUAL_KEY_Y,
	VIRTUAL_KEY_Z,
	VIRTUAL_KEY_LEFT_BRACKET, /* [ */
	VIRTUAL_KEY_BACKSLASH, /* \ */
	VIRTUAL_KEY_RIGHT_BRACKET, /* ] */
	VIRTUAL_KEY_GRAVE_ACCENT, /* ` */
	VIRTUAL_KEY_WORLD_1, /* non-US #1 */
	VIRTUAL_KEY_WORLD_2, /* non-US #2 */

	/* Function keys */
	VIRTUAL_KEY_ESCAPE,
	VIRTUAL_KEY_ENTER,
	VIRTUAL_KEY_TAB,
	VIRTUAL_KEY_BACKSPACE,
	VIRTUAL_KEY_INSERT,
	VIRTUAL_KEY_DELETE,
	VIRTUAL_KEY_RIGHT,
	VIRTUAL_KEY_LEFT,
	VIRTUAL_KEY_DOWN,
	VIRTUAL_KEY_UP,
	VIRTUAL_KEY_PAGE_UP,
	VIRTUAL_KEY_PAGE_DOWN,
	VIRTUAL_KEY_HOME,
	VIRTUAL_KEY_END,
	VIRTUAL_KEY_CAPS_LOCK,
	VIRTUAL_KEY_SCROLL_LOCK,
	VIRTUAL_KEY_NUM_LOCK,
	VIRTUAL_KEY_PRINT_SCREEN,
	VIRTUAL_KEY_PAUSE,
	VIRTUAL_KEY_F1,
	VIRTUAL_KEY_F2,
	VIRTUAL_KEY_F3,
	VIRTUAL_KEY_F4,
	VIRTUAL_KEY_F5,
	VIRTUAL_KEY_F6,
	VIRTUAL_KEY_F7,
	VIRTUAL_KEY_F8,
	VIRTUAL_KEY_F9,
	VIRTUAL_KEY_F10,
	VIRTUAL_KEY_F11,
	VIRTUAL_KEY_F12,
	VIRTUAL_KEY_KP_0,
	VIRTUAL_KEY_KP_1,
	VIRTUAL_KEY_KP_2,
	VIRTUAL_KEY_KP_3,
	VIRTUAL_KEY_KP_4,
	VIRTUAL_KEY_KP_5,
	VIRTUAL_KEY_KP_6,
	VIRTUAL_KEY_KP_7,
	VIRTUAL_KEY_KP_8,
	VIRTUAL_KEY_KP_9,
	VIRTUAL_KEY_KP_DECIMAL,
	VIRTUAL_KEY_KP_DIVIDE,
	VIRTUAL_KEY_KP_MULTIPLY,
	VIRTUAL_KEY_KP_SUBTRACT,
	VIRTUAL_KEY_KP_ADD,
	VIRTUAL_KEY_KP_ENTER,
	VIRTUAL_KEY_KP_EQUAL,
	VIRTUAL_KEY_LEFT_SHIFT,
	VIRTUAL_KEY_LEFT_CONTROL,
	VIRTUAL_KEY_LEFT_ALT,
	VIRTUAL_KEY_LEFT_SUPER,
	VIRTUAL_KEY_RIGHT_SHIFT,
	VIRTUAL_KEY_RIGHT_CONTROL,
	VIRTUAL_KEY_RIGHT_ALT,
	VIRTUAL_KEY_RIGHT_SUPER,
	VIRTUAL_KEY_MENU
};

#endif //HYPEROS_VIRTUAL_KEY_H_
