[package]
name = "hyper_kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
limine = "0.1.9"
log = "0.4.17"

[build-dependencies]
nasm-rs = { version = "0.2.4", features = ["parallel"] }
